obj-$(CONFIG_VIDEO_FIMC)	+= fimc/
obj-$(CONFIG_VIDEO_MFC10)	+= mfc10/
obj-$(CONFIG_VIDEO_MFC40)	+= mfc40/
obj-$(CONFIG_VIDEO_MFC50)	+= mfc50/
obj-$(CONFIG_VIDEO_POST)	+= post/
obj-$(CONFIG_VIDEO_POST)	+= tv/
obj-$(CONFIG_VIDEO_TV20)	+= tv20/
obj-$(CONFIG_VIDEO_ROTATOR)	+= rotator/
obj-$(CONFIG_VIDEO_JPEG)	+= jpeg/
obj-$(CONFIG_VIDEO_JPEG_V2)	+= jpeg_v2/
obj-$(CONFIG_VIDEO_G2D)		+= g2d/
obj-$(CONFIG_VIDEO_G3D)		+= g3d/
obj-$(CONFIG_VIDEO_GVG)		+= gvg/
obj-$(CONFIG_VIDEO_CMM)		+= cmm/
obj-$(CONFIG_VIDEO_RP)		+= rp/
 
EXTRA_CFLAGS += -Idrivers/media/video

