/* Pins which have pulldown or pullup */

inline void IO_InitPullResistors(void)
{
	PIN_ADD_MASK(TYPE_SUB_ID0,PIN_PULL_DOWN | PIN_PULL_UP);
	PIN_ADD_MASK(TYPE_SUB_ID1,PIN_PULL_DOWN | PIN_PULL_UP);
	PIN_ADD_MASK(WP_SD,PIN_PULL_UP);
	PIN_ADD_MASK(CD_SD,PIN_PULL_UP);
	PIN_ADD_MASK(HDD_DRQ,PIN_PULL_UP);
	PIN_ADD_MASK(HDD_DACK,PIN_PULL_UP);
	PIN_ADD_MASK(ON_OFF,PIN_PULL_UP);
	PIN_ADD_MASK(IGNITION,PIN_PULL_UP);
	PIN_ADD_MASK(ACPWR,PIN_PULL_UP);
	PIN_ADD_MASK(CHARGEFAULT,PIN_PULL_UP);
	PIN_ADD_MASK(BATT_TEMP_OVER,PIN_PULL_UP);
	PIN_ADD_MASK(DOCK_INT,PIN_PULL_UP);
	PIN_ADD_MASK(DOCK_SENSE,PIN_PULL_UP);
	PIN_ADD_MASK(DOCK_DESK_SENSE,PIN_PULL_UP);
	PIN_ADD_MASK(DOCK_CRIB_SENSE,PIN_PULL_UP);
	PIN_ADD_MASK(DOCK_VIB_SENSE,PIN_PULL_UP);
	PIN_ADD_MASK(DOCK_MOTOR_SENSE,PIN_PULL_UP);
	PIN_ADD_MASK(DOCK_RADIO_SENSE,PIN_PULL_UP);
	PIN_ADD_MASK(LIGHTS_DETECT,PIN_PULL_UP);
	PIN_ADD_MASK(CTS_DOCK,PIN_PULL_DOWN | PIN_PULL_UP);
	PIN_ADD_MASK(RTS_DOCK,PIN_PULL_DOWN | PIN_PULL_UP);
	PIN_ADD_MASK(TXD_DOCK,PIN_PULL_DOWN | PIN_PULL_UP);
	if (IO_HasPin(RXD_DOCK_INT))
	{
		PIN_ADD_MASK(RXD_DOCK,PIN_PULL_DOWN);
		PIN_ADD_MASK(RXD_DOCK_INT,PIN_PULL_DOWN);
	}
	else
	{
		PIN_ADD_MASK(RXD_DOCK,PIN_PULL_DOWN | PIN_PULL_UP);
	}
	PIN_ADD_MASK(LINEIN_DETECT,PIN_PULL_UP);
	PIN_ADD_MASK(AIN_DOCK_EINT,PIN_PULL_UP);
	if (IO_HaveCagliariDock()) {
		PIN_ADD_MASK(HEADPHONE_DETECT,PIN_PULL_DOWN);
	} else {
		PIN_ADD_MASK(HEADPHONE_DETECT,PIN_PULL_UP);
	}
	PIN_ADD_MASK(EXTMIC_DETECT,PIN_PULL_DOWN);
	PIN_ADD_MASK(LCD_ID,PIN_PULL_UP);
	PIN_ADD_MASK(USB_HOST_DETECT,PIN_PULL_UP);
	PIN_ADD_MASK(TOUCHPAD_SW,PIN_PULL_UP);
	PIN_ADD_MASK(FLEX_ID1,PIN_PULL_UP);
	PIN_ADD_MASK(FLEX_ID2,PIN_PULL_UP);
	PIN_ADD_MASK(FACTORY_TEST_POINT,PIN_PULL_UP);
	PIN_ADD_MASK(UART_RXD_IPOD,PIN_PULL_DOWN);
	PIN_ADD_MASK(UART_RXD_TMC,PIN_PULL_DOWN);
	PIN_ADD_MASK(PIC_DETECT,PIN_PULL_DOWN | PIN_PULL_UP);
	PIN_ADD_MASK(TXD_BT,PIN_PULL_DOWN | PIN_PULL_UP);
	PIN_ADD_MASK(RXD_BT,PIN_PULL_DOWN | PIN_PULL_UP);
	PIN_ADD_MASK(RTS_BT,PIN_PULL_DOWN | PIN_PULL_UP);
	PIN_ADD_MASK(CTS_BT,PIN_PULL_DOWN | PIN_PULL_UP);
	PIN_ADD_MASK(CAMRESET,PIN_PULL_DOWN | PIN_PULL_UP);
	PIN_ADD_MASK(CAMCLKOUT,PIN_PULL_DOWN | PIN_PULL_UP);
	PIN_ADD_MASK(CAMPCLK,PIN_PULL_DOWN | PIN_PULL_UP);
	PIN_ADD_MASK(CAMVSYNC,PIN_PULL_DOWN | PIN_PULL_UP);
	PIN_ADD_MASK(CAMHREF,PIN_PULL_DOWN | PIN_PULL_UP);
	PIN_ADD_MASK(CAMDATA0,PIN_PULL_DOWN | PIN_PULL_UP);
	PIN_ADD_MASK(CAMDATA1,PIN_PULL_DOWN | PIN_PULL_UP);
	PIN_ADD_MASK(CAMDATA2,PIN_PULL_DOWN | PIN_PULL_UP);
	PIN_ADD_MASK(CAMDATA3,PIN_PULL_DOWN | PIN_PULL_UP);
	PIN_ADD_MASK(CAMDATA4,PIN_PULL_DOWN | PIN_PULL_UP);
	PIN_ADD_MASK(CAMDATA5,PIN_PULL_DOWN | PIN_PULL_UP);
	PIN_ADD_MASK(CAMDATA6,PIN_PULL_DOWN | PIN_PULL_UP);
	PIN_ADD_MASK(CAMDATA7,PIN_PULL_DOWN | PIN_PULL_UP);

	if ( IO_GetGpsType() == GOGPS_ATH_AR1520 )
	{
		PIN_ADD_MASK(TXD_GPS,PIN_PULL_UP);
		PIN_ADD_MASK(RXD_GPS,PIN_PULL_UP);
	}
}
