#
# Makefile for the linux kernel.
#

# Object file lists.
obj-y	:= irvine-lcd-lms430.o irvine-lcd-lms350.o irvine-lcd-lms500.o irvine-lcd-a043fw05v4.o irvine-lcd-a050fw03v4.o irvine-lcd-lb043wq3.o irvine-lcd-ld050wq1.o irvine-lcd-lms500hf10.o irvine-lcd-lms430hf37.o irvine-lcd-lms501kf03.o irvine-lcd-lms606kf01.o
