# drivers/barcelona/pmic/Makefile
#
# Makefile for the PMIC drivers.
#
# Copyright (C) 2008 TomTom BV <http://www.tomtom.com/>
# Authors: Rogier Stam <rogier.stam@tomtom.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

obj-$(CONFIG_BARCELONA_LTC3455)		+= ltc3455-pmic.o
# EOF

