# drivers/barcelona/baro/Makefile
#
# Makefile for the Barometer driver.
#
# Copyright (C) 2007 TomTom BV <http://www.tomtom.com/>
# Authors: Rogier Stam <rogier.stam@tomtom.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

#obj-$(CONFIG_BARCELONA_BARO)		+= scp1000_baro.o scp1000_temp.o
obj-$(CONFIG_BARCELONA_BARO)		+= scp1000_baro.o
# EOF

