# drivers/barcelona/gadc/Makefile
#
# Makefile for the Generic ADC driver interface.
#
# Copyright (C) 2007 TomTom BV <http://www.tomtom.com/>
# Authors: Rogier Stam <rogier.stam@tomtom.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

obj-$(CONFIG_BARCELONA_GADC)		+= gadc_generic.o s3c24xx_gadc.o
# EOF

