#
# Makefile for the linux kernel.
#

# Object file lists.

obj-y := bcm_os_support.o bcm_divide.o bcm_log.o clkmgr.o armbusmtx.o chipmgr.o emi.o tahoe_opmode_perip_handlers.o tahoe_opmode_clock_switch.o tahoe_opmode_dram.o tahoe_opmode_perip.o tahoe_opmode_priv.o tahoe_opmode_pll.o tahoe_opmode_arm11.o tahoe_opmode_cmd_stats.o tahoe_opmode_cmd_params.o tahoe_opmode_low_level.o tahoe_opmode_synctops.o

EXTRA_CFLAGS += -ggdb 

