# drivers/barcelona/gacc/Makefile
#
# Makefile for the Barcelona accelerometer drivers.
#
# Copyright (C) 2004,2005 TomTom BV <http://www.tomtom.com/>
# Authors: Mark Vels <Mark.Vels@tomtom.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

obj-$(CONFIG_BARCELONA_GACC_SMB365)		+= smb365.o 
obj-$(CONFIG_BARCELONA_GACC_KXP74)		+= kxp74/
obj-$(CONFIG_BARCELONA_GADC_KXR94)		+= kxr94_gadc.o
# EOF

