# drivers/barcelona/rc/Makefile
#
# Makefile for the Barcelona remote control driver.
#
# Copyright (C) 2004,2005 TomTom BV <http://www.tomtom.com/>
# Author: Christian Daniel <cd@cdaniel.de>
# Author: Dimitry Andric <dimitry.andric@tomtom.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

obj-$(CONFIG_BARCELONA_RC)		+= rc.o

# EOF
