# S3c24XX Platform Support
snd-soc-s3c24xx-objs := s3c24xx-pcm.o
snd-soc-s3c24xx-i2s-objs := s3c24xx-i2s.o
snd-soc-s3c2412-i2s-objs := s3c2412-i2s.o
snd-soc-s3c64xx-i2s-objs := s3c64xx-i2s.o
snd-soc-s5p64xx-i2s-objs := s5p64xx-i2s.o
snd-soc-s3c2443-ac97-objs := s3c2443-ac97.o
snd-soc-s3c-i2s-v2-objs := s3c-i2s-v2.o
snd-soc-s3c-pcm-objs += s3c-pcm.o

obj-$(CONFIG_SND_S3C24XX_SOC) += snd-soc-s3c24xx.o
obj-$(CONFIG_SND_S3C24XX_SOC_I2S) += snd-soc-s3c24xx-i2s.o
obj-$(CONFIG_SND_S3C2443_SOC_AC97) += snd-soc-s3c2443-ac97.o
obj-$(CONFIG_SND_S3C2412_SOC_I2S) += snd-soc-s3c2412-i2s.o
obj-$(CONFIG_SND_S3C64XX_SOC_I2S) += snd-soc-s3c64xx-i2s.o
obj-$(CONFIG_SND_S5P64XX_SOC_I2S) += snd-soc-s5p64xx-i2s.o
obj-$(CONFIG_SND_S3C_I2SV2_SOC) += snd-soc-s3c-i2s-v2.o
obj-$(CONFIG_SND_S3C_PCM_SOC) += snd-soc-s3c-pcm.o

# S3C24XX Machine Support
snd-soc-neo1973-wm8753-objs := neo1973_wm8753.o
snd-soc-smdk2443-wm9710-objs := smdk2443_wm9710.o
snd-soc-ln2440sbc-alc650-objs := ln2440sbc_alc650.o
snd-soc-smdk64xx-wm8580-objs := smdk64xx_wm8580.o

snd-soc-torinos-wm8990-objs    := torinos_wm8990.o
snd-soc-seoul-adau1761-objs := seoul_adau1761.o
snd-soc-venice-adau1761-objs := venice_adau1761.o
snd-soc-cordoba-adau1761-objs := cordoba_adau1761.o
snd-soc-cordoba-s5m8751-objs := cordoba_s5m8751.o
snd-soc-cordoba-tlv320adc3101-objs := cordoba_tlv320adc3101.o
snd-soc-havana-s5m8751-objs := havana_s5m8751.o
snd-soc-havana-tlv320adc3101-objs := havana_tlv320adc3101.o
snd-soc-catania-s5m8751-objs := catania_s5m8751.o
snd-soc-catania-tlv320adc3101-objs := catania_tlv320adc3101.o
snd-soc-havana-bc6-objs := havana_bc6.o
snd-soc-catania-bc6-objs := catania_bc6.o

obj-$(CONFIG_SND_S3C24XX_SOC_NEO1973_WM8753) += snd-soc-neo1973-wm8753.o
obj-$(CONFIG_SND_S3C24XX_SOC_SMDK2443_WM9710) += snd-soc-smdk2443-wm9710.o
obj-$(CONFIG_SND_S3C24XX_SOC_LN2440SBC_ALC650) += snd-soc-ln2440sbc-alc650.o
obj-$(CONFIG_SND_S3C64XX_SOC_WM8580) += snd-soc-smdk64xx-wm8580.o

obj-$(CONFIG_SND_TORINOS_WM8990) += snd-soc-torinos-wm8990.o
obj-$(CONFIG_SND_SEOUL_ADAU1761) += snd-soc-seoul-adau1761.o
obj-$(CONFIG_SND_VENICE_ADAU1761) += snd-soc-venice-adau1761.o
obj-$(CONFIG_SND_CORDOBA_ADAU1761) += snd-soc-cordoba-adau1761.o
obj-$(CONFIG_SND_CORDOBA_S5M8751) += snd-soc-cordoba-s5m8751.o
obj-$(CONFIG_SND_CORDOBA_TLV320ADC3101) += snd-soc-cordoba-tlv320adc3101.o
obj-$(CONFIG_SND_HAVANA_S5M8751) += snd-soc-havana-s5m8751.o
obj-$(CONFIG_SND_HAVANA_TLV320ADC3101) += snd-soc-havana-tlv320adc3101.o
obj-$(CONFIG_SND_CATANIA_S5M8751) += snd-soc-catania-s5m8751.o
obj-$(CONFIG_SND_CATANIA_TLV320ADC3101) += snd-soc-catania-tlv320adc3101.o
obj-$(CONFIG_SND_HAVANA_BC6) += snd-soc-havana-bc6.o
obj-$(CONFIG_SND_CATANIA_BC6) += snd-soc-catania-bc6.o
