# drivers/barcelona/dock/Makefile
#
# Makefile for the Barcelona DOCK driver.
#
# Copyright (C) 2006 TomTom BV <http://www.tomtom.com/>
# Author: Dimitry Andric <dimitry.andric@tomtom.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

obj-$(CONFIG_BARCELONA_DOCK)		+= dock.o dock_cagliari.o dock_detect.o

# EOF
