# drivers/barcelona/usbmode/Makefile
#
# Makefile for the Barcelona usbmode kernel module
# This driver handles switching from and to different 
# usb modes
#
# Copyright (C) 2007 TomTom BV <http://www.tomtom.com/>
# Author: Kees Jongenburger <kees.jongenburger@tomtom.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

obj-$(CONFIG_BARCELONA_USBMODE)		+= usbmode.o
obj-$(CONFIG_BARCELONA_USBMODE_S3C24XX)		+= s3c24xx_usbmode.o

# EOF
