#################################################
# Makefile for FIMG-VG 
# 2009 (C) Samsung Electronics 
# Author : Jonghun Han <jonghun.han@samsung.com>
#################################################

obj-$(CONFIG_VIDEO_GVG)	+= s3c_fimgvg.o

EXTRA_CFLAGS += -Idrivers/media/video

