# drivers/barcelona/gprs/Makefile
#
# Makefile for the GPRS interface.
#
# Copyright (C) 2007 TomTom BV <http://www.tomtom.com/>
# Author: Rogier Stam <rogier.stam@tomtom.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

obj-$(CONFIG_GPRS_INTERFACE)		+= gprs.o adi6720.o faro.o mc55.o

# EOF
