# drivers/barcelona/Makefile
#
# Makefile for all the Barcelona device drivers.
#
# Copyright (C) 2004,2005 TomTom BV <http://www.tomtom.com/>
# Author: Dimitry Andric <dimitry.andric@tomtom.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

obj-$(CONFIG_MACH_TOMTOMGO)		+= pmic/
obj-$(CONFIG_MACH_TOMTOMGO)		+= hw/
obj-$(CONFIG_MACH_TOMTOMGO)		+= adc/
obj-$(CONFIG_MACH_TOMTOMGO)		+= gadc/
obj-$(CONFIG_MACH_TOMTOMGO)		+= baro/
obj-$(CONFIG_MACH_TOMTOMGO)		+= gpio/
obj-$(CONFIG_MACH_TOMTOMGO)		+= acc/
obj-$(CONFIG_MACH_TOMTOMGO)		+= gacc/
obj-$(CONFIG_MACH_TOMTOMGO)		+= bat/
obj-$(CONFIG_MACH_TOMTOMGO)		+= gps/
obj-$(CONFIG_MACH_TOMTOMGO)		+= pwm/
obj-$(CONFIG_MACH_TOMTOMGO)		+= ts/
obj-$(CONFIG_MACH_TOMTOMGO)		+= tsinput/
obj-$(CONFIG_MACH_TOMTOMGO)		+= sound/
obj-$(CONFIG_MACH_TOMTOMGO)		+= rc/
obj-$(CONFIG_MACH_TOMTOMGO)		+= buz/
obj-$(CONFIG_MACH_TOMTOMGO)		+= gyro/
obj-$(CONFIG_MACH_TOMTOMGO)		+= usbmode/
obj-$(CONFIG_MACH_TOMTOMGO)		+= buspower/
obj-$(CONFIG_MACH_TOMTOMGO)		+= dock/
obj-$(CONFIG_MACH_TOMTOMGO)		+= gprs/

# EOF
