# drivers/barcelona/acc/Makefile
#
# Makefile for the Barcelona accelerometer driver.
#
# Copyright (C) 2004,2005 TomTom BV <http://www.tomtom.com/>
# Authors: Dimitry Andric <dimitry.andric@tomtom.com>
#          Jeroen Taverne <jeroen.taverne@tomtom.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

obj-$(CONFIG_BARCELONA_ACC)		+= acc.o
obj-$(CONFIG_BARCELONA_ACC)		+= acciic.o
obj-$(CONFIG_BARCELONA_ACC)		+= mxr2312.o
obj-$(CONFIG_BARCELONA_ACC)		+= mxr3999.o
obj-$(CONFIG_BARCELONA_ACC)		+= mxm9301.o
obj-$(CONFIG_BARCELONA_ACC)		+= mxr9500.o

# EOF
