# drivers/barcelona/gacc/Makefile
#
# Makefile for the Barcelona gyro drivers.
#
# Copyright (C) 2007 TomTom BV <http://www.tomtom.com/>
# Authors: Mark Vels <Mark.Vels@tomtom.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.


#Please Note: only on of these two can be active at a time!
obj-$(CONFIG_BARCELONA_GYRO_FUJITSU)			+= gyro.o 
obj-$(CONFIG_BARCELONA_GYRO_ING300)			+= gyro.o 
# EOF

