# drivers/barcelona/buz/Makefile
#
# Makefile for the TomTom GO buzzer driver.
#
# Copyright (C) 2006 TomTom BV <http://www.tomtom.com/>
# Author: Dimitry Andric <dimitry.andric@tomtom.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

obj-$(CONFIG_BARCELONA_BUZ)		+= buz.o

# EOF
