# drivers/video/tomtom/Makefile
#
# Makefile for the TomTom GO video driver.
#
# Copyright (C) 2005,2006 TomTom BV <http://www.tomtom.com/>
# Author: Dimitry Andric <dimitry.andric@tomtom.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

obj-$(CONFIG_FB_TTGFB) += ttgfb.o lq043t3dw02.o lq043t3dw01.o a035qn02.o lq035q1dg.o lq035q1dg04.o lq043t1.o lte246qv.o ltp400wq.o lte430wq.o ltv350qv.o lms350gf.o lms350gf20.o lms430hf12.o nec.o framerate.o
obj-$(CONFIG_FB_TTGFB) += ttgfb.o s3c2443_tft.o s3c24xx_lcd.o lq043t3dw02.o lq043t3dw01.o a035qn02.o a043fw03.o lq035q1dg.o lq035q1dg04.o lq043t1.o lte246qv.o ltp400wq.o lte430wq.o ltv350qv.o lms350gf.o lms350gf20.o lms430hf12.o nec.o framerate.o
obj-$(CONFIG_FB_TTGFB) += ttgfb.o s3c2443_tft.o s3c24xx_lcd.o lq043t3dw02.o lq043t3dw01.o \
	a035qn02.o a043fw03.o lq035q1dg.o lq035q1dg04.o lq043t1.o lte246qv.o ltp400wq.o lte430wq.o \
	ltv350qv.o lms350gf.o lms350gf20.o lms430hf12.o lms500hf01.o a050fw02v2.o lb043wq3.o nec.o \
	a050fw03v2.o ld050wq1.o t35qta530.o framerate.o

# EOF
