# drivers/tomtom/lcm/Makefile
#
# Copyright (C) 2012 TomTom BV <http://www.tomtom.com/>
# Author: Will Lin <Will.Lin@tomtom.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

obj-$(CONFIG_TOMTOM_LCM_LMS606KF01)	+= lms606kf01.o
