# Backlight & LCD drivers

obj-$(CONFIG_LCD_CLASS_DEVICE)     += lcd.o
obj-$(CONFIG_BACKLIGHT_CLASS_DEVICE) += backlight.o
obj-$(CONFIG_BACKLIGHT_S3C)	+= s3c_bl.o
obj-$(CONFIG_BACKLIGHT_S3C_LTC)	+= s3c_bl_ltc.o
obj-$(CONFIG_BACKLIGHT_CORGI)	+= corgi_bl.o
