#
# Makefile for the LTT objects.
#

obj-$(CONFIG_LTT)			+= ltt-core.o
obj-$(CONFIG_LTT_TRACER)		+= ltt-tracer.o
obj-$(CONFIG_LTT_RELAY)			+= ltt-relay.o
obj-$(CONFIG_LTT_RELAY_LOCKED)		+= ltt-relay-locked.o
obj-$(CONFIG_LTT_RELAY_ALLOC)		+= ltt-relay-alloc.o
obj-$(CONFIG_LTT_NETLINK_CONTROL)	+= ltt-control.o
obj-$(CONFIG_LTT_SERIALIZE)		+= ltt-serialize.o
obj-$(CONFIG_LTT_STATEDUMP)		+= ltt-statedump.o
obj-$(CONFIG_LTT_MARKER_CONTROL)	+= ltt-marker-control.o
obj-$(CONFIG_LTT_TRACEPROBES)		+= probes/
obj-$(CONFIG_LTT_FTRACE)		+= ltt-ftrace.o
