#
# Makefile for the 'Next Generation' Flash File System (NGFFS)
#
# $Id: Makefile,v 1.3 2005/07/12 11:21:40 koen Exp $
#

obj-$(CONFIG_NGFFS_FS) += ngffs.o

ngffs-${CONFIG_NGFFS_FS} := crc.o chunk.o dir.o file.o flash.o garbage.o inode.o super.o sysfile.o

