# drivers/barcelona/buspower/Makefile
#
# Makefile for the Barcelona buspower kernel module
# This driver monitors the vbus and notifies interrested
# parties
#
# Copyright (C) 2007 TomTom BV <http://www.tomtom.com/>
# Author: Kees Jongenburger <kees.jongenburger@tomtom.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

obj-$(CONFIG_BARCELONA_BUSPOWER)	+= buspower.o

# EOF
